server:
  port: 80
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/webscraping
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true